src/pkgcheck/checks/repo_metadata.py
Deprecated profiles still should be listed in 'profiles.desc' to
have a chance of repoman to be checked as a real profile for sanity.
'profiles.desc' is also a good place to add detailed deprecation comment.
Let's complain about unreferenced 'deprecated' profiles.
Closes: https://github.com/pkgcore/pkgcheck/issues/77
=> checks/repo_metadata.py: flag as UnusedProfileDirs deprecated profiles

src/pkgcheck/checks/deprecated.py
Signed-off-by: Michał Górny <mgorny@gentoo.org>
=> deprecated: Mark user.eclass deprecated, in favor of GLEP 81

src/pkgcheck/addons.py
Pass '--pretty=medium' to git log calls, as that is the format parser
expects.  This fixes parsing errors when .git/config specifies
a different default pretty format.
=> addons: Pass explicit --pretty=medium to git log

src/pkgcheck/checks/profiles.py
Use profile inheritance to determine whether the 'newer' EAPI is
a superset of an 'older' EAPI rather than lexical comparison.
=> RepoProfilesCheck: use inheritance instead of lexical EAPI name cmp

src/pkgcheck/checks/git.py, tests/checks/test_git.py
Closes: https://github.com/pkgcore/pkgcheck/issues/344
=> GitCommitMessageCheck: Allow version to be prefixed with "v"

src/pkgcheck/checks/eclass.py, testdata/data/repos/eclass/EclassParseCheck/EclassExportFuncsBeforeInherit/expected.json, testdata/data/repos/eclass/EclassParseCheck/EclassExportFuncsBeforeInherit/fix.patch, testdata/repos/eclass/EclassParseCheck/EclassExportFuncsBeforeInherit/EclassExportFuncsBeforeInherit-1.ebuild, testdata/repos/eclass/eclass/another-src_prepare.eclass, testdata/repos/eclass/eclass/export-funcs-before-inherit.eclass
The behavior for handling EXPORT_FUNCTIONS before inherit is not
consistent across package managers.  Enforce calling it after inherit
to guarantee consistent behavior.
=> Add a check for eclasses calling EXPORT_FUNCTIONS before inherit

src/pkgcheck/checks/eclass.py, testdata/data/repos/standalone/EclassUsageCheck/DeprecatedEclassFunction/expected.json, testdata/data/repos/standalone/EclassUsageCheck/DeprecatedEclassVariable/expected.json, testdata/repos/standalone/EclassUsageCheck/DeprecatedEclassFunction/DeprecatedEclassFunction-0.ebuild, testdata/repos/standalone/EclassUsageCheck/DeprecatedEclassVariable/DeprecatedEclassVariable-0.ebuild, testdata/repos/standalone/eclass/go-module.eclass
Resolves: https://github.com/pkgcore/pkgcheck/issues/373
Resolves: https://github.com/pkgcore/pkgcheck/issues/374
<details>
<summary>Example output</summary>
```
app-admin/gopass
UnstableOnly: for arches: [ ppc64, x86 ], all versions are unstable: [ 1.12.6, 1.12.7, 1.13.0 ]
DeprecatedEclassVariable: version 1.12.6: uses deprecated variable on line 8: EGO_SUM (no replacement)
DeprecatedEclassFunction: version 1.12.6: uses deprecated function on line 494: go-module_set_globals (no replacement)
PotentialStable: version 1.12.6: slot(0), stabled arch: [ amd64 ], potentials: [ ~ppc64, ~x86 ]
DeprecatedEclassVariable: version 1.12.7: uses deprecated variable on line 8: EGO_SUM (no replacement)
DeprecatedEclassFunction: version 1.12.7: uses deprecated function on line 498: go-module_set_globals …
```
=> new check: usage of deprecated variables or functions

src/pkgcheck/checks/network.py, testdata/repos/network/FetchablesUrlCheck/DeadUrl/DeadUrl-0.ebuild, testdata/repos/network/HomepageUrlCheck/DeadUrl/DeadUrl-0.ebuild
Limit network checks to ftp, http and https URLs, in order to avoid
DeadUrl reports that are duplicate to e.g. BadHomepage.
Fixes #372
=> network: Do not attempt to verify URL with unknown protocol

src/pkgcheck/checks/network.py
Apply metadata.xml URL check results to the newest package version
rather than the oldest, in order to fix displaying them when multiple
package versions are available.  Since the result objects are subclasses
of FilteredVersionResult, they are filtered out when they do not apply
to the newest version.
Closes: https://github.com/pkgcore/pkgcheck/issues/385
=> network: Fix metadata.xml results when old version is present

src/pkgcheck/checks/network.py, src/pkgcheck/objects.py, src/pkgcheck/results.py, src/pkgcheck/sources.py
Replace the resulting filter in network checks with source filtering. This has the advantage that the checks are actually done only for the interesting versions, rather than being done (and therefore the requests sent) for old versions, and then discarded. This uses a new source class that is roughly based on newest version filtering but actually works.
=> network: Limit checks to newest versions in slot (correctly)

src/pkgcheck/checks/git.py
When using `_RemovalRepo` for previous git state repo, it uses
`UnconfiguredTree::_pkg_filter` as default pkg_filter. During the
check for various bad file, it tries to parse the ebuild, which in
turn tries to check the usage around inherited eclasses - which
doesn't exist in this repo.
In theory, the setting of masters repo as the original one should
suffice, but it doesn't in practice. For now, let's copy the eclass
content so at least this very important check is done!
=> GitPkgCommitsCheck: fix files check

src/pkgcheck/checks/git.py, tests/checks/test_git.py
Idea was suggested by radhermit. I have also added a test which fails in original situation and passes now.
Fixes: 9ed3caaf86adf1141d9085683b37c5030eded2f2
=> GitPkgCommitsCheck: fix the eclass copying for RemovalRepo

contrib/emacs/flycheck-pkgcheck.el, src/pkgcheck/reporters.py, tests/test_reporters.py
Bug: https://github.com/pkgcore/pkgcheck/issues/417
Signed-off-by: Maciej Barć <xgqt@gentoo.org>
=> contrib/emacs: add flycheck-pkgcheck.el - Flycheck checker for ebuilds

src/pkgcheck/addons/git.py
When using GitLog class, it runs the git commands with clean git config, (aka it uses an empty one) which results in inability to use pkgcheck scan on overlays (as it tries to access system's gentoo repo, which is owned by root). If the user set safe.directory in his config, it will still not work, as we override user's config.
Fix it by creating a temporary file, which we fill with minimal config which disables safe.directory feature, and passing it as the config file to the git log command.
Resolves: https://github.com/pkgcore/pkgcheck/issues/412
=> addons/git: fix interaction with git's safe.directory

src/pkgcheck/checks/codingstyle.py, testdata/repos/eclass/InheritsCheck/MissingInherits/MissingInherits-0.ebuild
tree-sitter-bash uses type variable_name for the variable names when
unset is used. Add a special case when a variable_name is detected whose
parent is unset_command.
Resolves: https://github.com/pkgcore/pkgcheck/issues/353
=> MissingInherits: fix false positives with unset

src/pkgcheck/checks/git.py, tests/checks/test_git.py
When doing the checks for commit summary, add an exception to the rule
for acct-* packages, so the version added isn't a must for them.
Resolves: https://github.com/pkgcore/pkgcheck/issues/433
=> BadCommitSummary: version check should be ignored for acct-* packages

src/pkgcheck/checks/reserved.py, testdata/data/repos/eclass/EclassReservedCheck/EclassReservedName/expected.json, testdata/repos/eclass/eclass/reserved.eclass, tests/scripts/test_pkgcheck_scan.py
Using reserved variable names, and not only defining, is prohibited.
Also add new exceptions to the list of reserved names.
There was no need to update the implementation for functions calls, as the current query catches them.
=> ReservedNameCheck: update rules for usage of reserved

src/pkgcheck/checks/git.py
Sadly, I still have no facility to cleanup on exit the tmpdir, so for now add prefix and suffix to the dirs, to make it clear to users who spams their tmpdir.
=> GitPkgCommitsCheck: add prefix and suffix for tmpdir

src/pkgcheck/checks/codingstyle.py, testdata/data/repos/eclass/EclassUnquotedVariablesCheck/EclassUnquotedVariable/expected.json, testdata/repos/eclass/eclass/unquotedvariable.eclass
The `:` command is used for various setting of variables, while not using the value. As a result, `: ${VAR:=${D}}` is fine, as it won't use spaced variable, but `foo ${VAR:=${D}}` will use the unquoted result of D.
=> UnquotedVariablesCheck: add `:` to message_commands

src/pkgcheck/checks/codingstyle.py, src/pkgcheck/checks/metadata_xml.py, src/pkgcheck/checks/python.py, src/pkgcheck/checks/whitespace.py, src/pkgcheck/reporters.py, src/pkgcheck/results.py, tests/test_reporters.py
All multiple lines results are split into separate output lines, making it much nicer to use when using flycheck. It also does best effort to clean the lines list from `desc` so the output is shorter and cleaner.
@xgqt can you please review how it looks for you now?
Resolves: https://github.com/pkgcore/pkgcheck/issues/442
=> FlycheckReporter: split multiple line results

src/pkgcheck/checks/cleanup.py, tests/checks/test_cleanup.py
Add an option for considering only stable versions when checking for redundant versions.
This is useful for cases of cleanup after successful stabilization.
My logic is: for each redundant version, check if it is redundant by a ebuild which has a stable keyword
=> RedundantVersionCheck: add `--stable-only` option

.github/workflows/manylinux.sh, .github/workflows/release.yml
Because of all the targets, it took ~45 minutes to make a release. So split it into multiple jobs that pass the artifacts to a final deploy step.
=> ci: split release workflow into parallel jobs

src/pkgcheck/checks/codingstyle.py, testdata/data/repos/standalone/MetadataVarCheck/StaticSrcUri/expected.json, tests/checks/test_codingstyle.py
- handle various new cases, and a little less permissive regex
- add cases of usage of `ver_rs` and `ver_cut`
- suggest the user with replacement
The new logic:
1. A match must start with `/` or `PN[-._]?` - I don't want random suggestion because it somehow matches somewhere in commit id.
2. Possible separator of `[v]?`
3. After that I match all the following variants (of course the literal and not variable):
- `${P}`
- `${PV}`
- `$(ver_cut 1-n)` where `n` > 1 - I skip the variant of `$(ver_cut 1)` because of large amount of false positives
- `$(ver_rs 1-n '#')` where `n` > 0 and `#` is one of `Ɛ` (empty str), `_`, `-`. Can add other symbols.
Sadly, the code for generating the regex became an abomination.
<details>
<summary>new StaticSrcUri results on gentoo tree (v2)</summary>
``` …
```
=> StaticSrcUri: handle more cases

src/pkgcheck/checks/git.py
When we are performing `--commits` scan over a commit range that have at least 2 commits that drop a version from the same package, we can have a state of the temporary "removal repo" that it expects one of the removed ebuilds.
This is because the check is fed package after package, with the list of all removals of this package in a list. When creating the archival repo, we need to select the commit from which to "archive", and we select the first commit in the list. This is not always the right commit, as it can be the second or third commit that removes the a version. As a result we have an archival repo that expects all version to exist, but one of them might be missing.
By selecting the commit with the lowest commit date, we ensure the right commit is selected, and all removed ebuilds …
=> GitPkgCommitsCheck: fix archival repo from multiple removals

src/pkgcheck/checks/__init__.py, src/pkgcheck/pipeline.py, src/pkgcheck/runners.py
Add a special runner which is run only on main process, and after the synchronous runners. This is useful for runners which must not be run in parallel, like the git checks.
Resolves: https://github.com/pkgcore/pkgcheck/issues/326
=> Fixes for `pkgcheck scan --commit`

src/pkgcheck/checks/acct.py, tests/checks/test_acct.py
Load UID and GID range from `metadata/qa-policy.conf` under the repo, validate the format is as expected, and use the values to set expected ids.
Resolves: https://github.com/pkgcore/pkgcheck/issues/356
---
I mainly need a review of the class' docs changes I did, that they are sane.
=> AcctCheck: use `metadata/qa-policy.conf` for dynamic id range

src/pkgcheck/checks/metadata.py, testdata/data/repos/standalone/VirtualProvidersCheck/VirtualWithBdepend/expected.json, testdata/data/repos/standalone/VirtualProvidersCheck/VirtualWithDepend/expected.json, testdata/data/repos/standalone/VirtualProvidersCheck/VirtualWithSingleProvider/expected.json, testdata/repos/standalone/profiles/desc/elibc.desc, testdata/repos/standalone/profiles/package.deprecated, testdata/repos/standalone/virtual/VirtualWithBdepend/VirtualWithBdepend-0.ebuild, testdata/repos/standalone/virtual/VirtualWithBdepend/VirtualWithBdepend-1.ebuild, testdata/repos/standalone/virtual/VirtualWithDepend/VirtualWithDepend-0.ebuild, testdata/repos/standalone/virtual/VirtualWithDepend/VirtualWithDepend-1.ebuild, testdata/repos/standalone/virtual/VirtualWithSingleProvider1/VirtualWithSingleProvider1-0.ebuild, testdata/repos/standalone/virtual/VirtualWithSingleProvider2/VirtualWithSingleProvider2-0.ebuild, testdata/repos/standalone/virtual/VirtualWithSingleProvider3/VirtualWithSingleProvider3-0.ebuild, testdata/repos/standalone/virtual/VirtualWithSingleProvider3/VirtualWithSingleProvider3-1.ebuild, testdata/repos/standalone/virtual/VirtualWithSingleProvider4/VirtualWithSingleProvider4-0.ebuild, testdata/repos/standalone/virtual/VirtualWithSingleProvider4/VirtualWithSingleProvider4-1.ebuild, testdata/repos/standalone/virtual/VirtualWithSingleProvider5/VirtualWithSingleProvider5-0.ebuild, testdata/repos/standalone/virtual/VirtualWithSingleProvider6/VirtualWithSingleProvider6-0.ebuild
- check for virtual package defining DEPEND or BDEPEND
- check for virtual package with a single provider across versions
- All of them of `Warning` level
The logic for the single provider is:
1. Every version has one provider (compares full atom, for cases like when we depend on one of use flags)
2. Collecting all unversioned unslotted RDEPENDs gives us only one match --> to which we should replace the virtual.
Closes: https://bugs.gentoo.org/744784
<details>
<summary>results over gentoo repo</summary>
```
virtual/acl
VirtualWithSingleProvider: virtual package with a single provider: sys-apps/acl
virtual/blas
VirtualWithDepend: version 3.8: virtual package with a DEPEND defined
virtual/cblas
VirtualWithDepend: version 3.8: virtual package with a DEPEND defined
virtual/imap-c-client …
```
=> VirtualProvidersCheck: new check for providers issues

src/pkgcheck/checks/codingstyle.py, testdata/data/repos/standalone/NonPosixCheck/NonPosixHeadTailUsage/expected.json, testdata/data/repos/standalone/NonPosixCheck/NonPosixHeadTailUsage/fix.patch, testdata/repos/standalone/NonPosixCheck/NonPosixHeadTailUsage/NonPosixHeadTailUsage-0.ebuild, testdata/repos/standalone/NonPosixCheck/NonPosixHeadTailUsage/NonPosixHeadTailUsage-1.ebuild
New warning for non-POSIX compliant head or tail without -n.
Closes: https://bugs.gentoo.org/558360
=> NonPosixHeadTailUsage: new check

src/pkgcheck/checks/eclass.py, testdata/data/repos/eclass/EclassUsageCheck/EclassUserVariableUsage/expected.json, testdata/repos/eclass/EclassUsageCheck/EclassUserVariableUsage/EclassUserVariableUsage-0.ebuild
Check ebuilds for overriding eclass' user variables.
Resolves: https://github.com/pkgcore/pkgcheck/issues/512
=> EclassUsageCheck: check for setting user variables in ebuilds

src/pkgcheck/checks/profiles.py, testdata/data/repos/profiledir/RepoProfilesCheck/ArchesOutOfSync/expected.json, testdata/data/repos/profiledir/RepoProfilesCheck/ArchesOutOfSync/fix.sh, testdata/repos/profiledir/profiles/arches.desc
Resolves: https://github.com/pkgcore/pkgcheck/issues/526
=> ArchesMisSync: check for arch.list <-> arches.desc missync

src/pkgcheck/checks/git.py, tests/checks/test_git.py
Currently it is in first stages, which need a lot of work:
Resolves: https://github.com/pkgcore/pkgcheck/issues/493
=> GitPkgCommitsCheck: catch SRC_URI mistakes

src/pkgcheck/bash/__init__.py, src/pkgcheck/checks/reserved.py, testdata/data/repos/standalone/EbuildReservedCheck/EbuildSemiReservedName/expected.json, testdata/repos/standalone/EbuildReservedCheck/EbuildSemiReservedName/EbuildSemiReservedName-0.ebuild
<details><summary>Gentoo results</summary>
```
app-editors/padre
EbuildSemiReservedName: version 1.0.0-r2: line 19: uses semi-reserved variable name "TDEPEND", likely to clash with future EAPIs
app-text/texlive-core
EbuildSemiReservedName: version 2021-r2: line 133: uses semi-reserved variable name "B", likely to clash with future EAPIs
EbuildSemiReservedName: version 2021-r3: line 134: uses semi-reserved variable name "B", likely to clash with future EAPIs
EbuildSemiReservedName: version 2021-r6: line 134: uses semi-reserved variable name "B", likely to clash with future EAPIs
dev-lang/mlton
EbuildSemiReservedName: version 20180207: line 41: uses semi-reserved variable name "B", likely to clash with future EAPIs
EbuildSemiReservedName: version 20180207: line 42: uses semi-reserved …
```
=> EbuildReservedCheck: check for semi-reserved names

src/pkgcheck/checks/git.py, tests/checks/test_git.py
@thesamesam I've taken your notes in the issue to build the best description I could, but I suspect I've made the grammar a little worse that way.
Resolves: https://github.com/pkgcore/pkgcheck/issues/557
=> GitPkgCommitsCheck: add check for EAPI change without revbump

src/pkgcheck/checks/metadata.py, testdata/data/repos/standalone/StaleLiveCheck/StaleLiveEAPI/expected.json, testdata/repos/standalone/StaleLiveCheck/StaleLiveEAPI/StaleLiveEAPI-0.ebuild, testdata/repos/standalone/StaleLiveCheck/StaleLiveEAPI/StaleLiveEAPI-1.9999.ebuild, testdata/repos/standalone/StaleLiveCheck/StaleLiveEAPI/StaleLiveEAPI-1.ebuild, testdata/repos/standalone/StaleLiveCheck/StaleLiveEAPI/StaleLiveEAPI-2.1.ebuild, testdata/repos/standalone/StaleLiveCheck/StaleLiveEAPI/StaleLiveEAPI-2.9999.ebuild, testdata/repos/standalone/StaleLiveCheck/StaleLiveEAPI/StaleLiveEAPI-2.ebuild, testdata/repos/standalone/StaleLiveCheck/StaleLiveEAPI/StaleLiveEAPI-3.1.ebuild, testdata/repos/standalone/StaleLiveCheck/StaleLiveEAPI/StaleLiveEAPI-3.9999.ebuild, testdata/repos/standalone/StaleLiveCheck/StaleLiveEAPI/StaleLiveEAPI-3.ebuild, testdata/repos/standalone/StaleLiveCheck/StaleLiveEAPI/StaleLiveEAPI-4.9999.ebuild
<details><summary>Gentoo results</summary>
```
app-arch/xz-utils
StaleLiveEAPI: version 9999: live ebuild uses older EAPI=7 than release ebuilds (EAPI=8)
app-crypt/eid-mw
StaleLiveEAPI: version 9999: live ebuild uses older EAPI=7 than release ebuilds (EAPI=8)
app-crypt/hashcat
StaleLiveEAPI: version 9999: live ebuild uses older EAPI=7 than release ebuilds (EAPI=8)
app-i18n/libpinyin
StaleLiveEAPI: version 9999: live ebuild uses older EAPI=7 than release ebuilds (EAPI=8)
app-misc/dateutils
StaleLiveEAPI: version 9999: live ebuild uses older EAPI=7 than release ebuilds (EAPI=8)
app-misc/radeontop
StaleLiveEAPI: version 9999: live ebuild uses older EAPI=7 than release ebuilds (EAPI=8)
app-misc/screen
StaleLiveEAPI: version 9999: live ebuild uses older EAPI=7 than release ebuilds (EAPI=8) …
```
=> StaleLiveCheck: new check for stale live eapi

src/pkgcheck/checks/rust.py, testdata/data/repos/standalone/RustCheck/SuboptimalCratesSeparator/expected.json, testdata/data/repos/standalone/RustCheck/SuboptimalCratesSeparator/fix.patch, testdata/data/repos/standalone/RustCheck/SuboptimalCratesURICall/expected.json, testdata/data/repos/standalone/RustCheck/SuboptimalCratesURICall/fix.patch, testdata/repos/standalone/RustCheck/SuboptimalCratesSeparator/SuboptimalCratesSeparator-0.ebuild, testdata/repos/standalone/RustCheck/SuboptimalCratesURICall/SuboptimalCratesURICall-0.ebuild, testdata/repos/standalone/RustCheck/SuboptimalCratesURICall/SuboptimalCratesURICall-1.ebuild, testdata/repos/standalone/RustCheck/SuboptimalCratesURICall/SuboptimalCratesURICall-2.ebuild, testdata/repos/standalone/eclass/cargo.eclass
Resolves: https://github.com/pkgcore/pkgcheck/issues/586
=> RustCheck: new crates checks

src/pkgcheck/checks/profiles.py
https://github.com/pkgcore/pkgcheck/issues/588
=> ProfilesCheck: for unknown packages, mention last match removed

src/pkgcheck/checks/ruby.py, testdata/data/repos/python/RubyCompatCheck/RubyCompatUpdate/expected.json, testdata/repos/python/RubyCompatCheck/RubyCompatUpdate/RubyCompatUpdate-0.ebuild, testdata/repos/python/RubyCompatCheck/RubyCompatUpdate/RubyCompatUpdate-1.ebuild, testdata/repos/python/RubyCompatCheck/RubyCompatUpdate/RubyCompatUpdate-2.ebuild, testdata/repos/python/dev-lang/ruby/ruby-2.7.ebuild, testdata/repos/python/dev-lang/ruby/ruby-3.0.ebuild, testdata/repos/python/dev-lang/ruby/ruby-3.1.ebuild, testdata/repos/python/dev-lang/ruby/ruby-3.2.ebuild, testdata/repos/python/eclass/ruby-ng.eclass, testdata/repos/python/profiles/desc/ruby_targets.desc, testdata/repos/python/stub/ruby-dep-old/ruby-dep-old-0.ebuild, testdata/repos/python/stub/ruby-dep/ruby-dep-0.ebuild
I think the `ruby-ng.eclass` is a real abomination I've created. I've extracted parts from real ruby-ng, modified as I needed, took shortcuts and more. I hope no sane person will use this abomination, we need to cast in into the fire :)
Resolves: https://github.com/pkgcore/pkgcheck/issues/304
=> RubyCompatCheck: new check for new USE_RUBY compatible values

src/pkgcheck/checks/repo_metadata.py, testdata/data/repos/standalone/ManifestCheck/DeprecatedManifestHash/expected.json, testdata/data/repos/standalone/RepoManifestHashCheck/DeprecatedRepoHash/expected.json, testdata/repos/standalone/metadata/layout.conf
2 new checks:
- `RepoManifestHashCheck`: check for deprecated repo config
- `DeprecatedManifestHash`: check for deprecated checksums in manifest files
Resolves: https://github.com/pkgcore/pkgcheck/issues/508
=> new checks for deprecated manifest hashes

src/pkgcheck/checks/perl.py, tests/checks/test_perl.py
@akhuettel @thesamesam So here it is. A 
[huge amount of matches](https://github.com/pkgcore/pkgcheck/files/11931201/3MHLRYTHV.txt) across the repo. After some talks on IRC (#-perl) this is done as optional check, so folks need to enable `PerlCheck` for this result to appear.
I'm fine with any decision (merge or decline), so don't feel obligated 😄 
Resolves: https://github.com/pkgcore/pkgcheck/issues/593
=> PerlCheck: check versioned virtual perl dependencies

src/pkgcheck/checks/codingstyle.py, testdata/data/repos/standalone/VariableScopeCheck/EbuildVariableScope/expected.json, testdata/data/repos/standalone/VariableScopeCheck/EbuildVariableScope/fix.patch, testdata/repos/standalone/VariableScopeCheck/EbuildVariableScope/EbuildVariableScope-0.ebuild
@ulm please verify I collected correctly all the variables from the table. I've taken all variables that have "consistent" value set to "no" in the table.
<details>
<summary>Results excluding VERIFY_SIG_OPENPGP_KEY_PATH</summary>
```
app-admin/conky
VariableScope: version 1.17.0-r1: variable 'ROOT' used in 'global scope' on line: 110
VariableScope: version 1.19.2-r1: variable 'ROOT' used in 'global scope' on line: 110
app-mobilephone/adebar
VariableScope: version 2.4.1: variable 'ROOT' used in 'global scope' on line: 26
app-text/highlight
VariableScope: version 4.1: variable 'D' used in 'global scope' on line: 46
VariableScope: version 4.6: variable 'D' used in 'global scope' on line: 47
dev-perl/Crypt-OpenSSL-Random
VariableScope: version 0.150.0-r1: variable 'ESYSROOT' used in 'global …
```
=> VariableScopeCheck: also check for wrong usage on global scope

src/pkgcheck/checks/codingstyle.py, testdata/data/repos/standalone/GlobCheck/GlobDistdir/expected.json, testdata/repos/standalone/GlobCheck/GlobDistdir/GlobDistdir-0.ebuild
This time I decided to try to implement using tree-sitter query language. It is faster than in python scan, which is nice.
```
$ pkgcheck scan -c GlobCheck
games-strategy/homm2-gold-gog
GlobDistdir: version 1.1.2.1.33438: line 40: unsafe filename expansion used with DISTDIR: "${DISTDIR}"/setup_heroes*.exe
media-gfx/darktable
GlobDistdir: version 4.2.1: line 174: unsafe filename expansion used with DISTDIR: "${DISTDIR}"/${PN}-usermanual-${DOC_PV}.*.pdf
GlobDistdir: version 4.4.1: line 171: unsafe filename expansion used with DISTDIR: "${DISTDIR}"/${PN}-usermanual-${DOC_PV}.*.pdf
GlobDistdir: version 4.4.2: line 171: unsafe filename expansion used with DISTDIR: "${DISTDIR}"/${PN}-usermanual-${DOC_PV}.*.pdf
```
Resolves: https://github.com/pkgcore/pkgcheck/issues/605
=> GlobDistdir: check for glob usage with DISTDIR

src/pkgcheck/checks/eclass.py, testdata/data/repos/standalone/EclassManualDepsCheck/GoMissingDeps/expected.json, testdata/data/repos/standalone/EclassManualDepsCheck/RubyMissingDeps/expected.json, testdata/data/repos/standalone/EclassManualDepsCheck/RubyMissingDeps/fix.patch, testdata/data/repos/standalone/EclassManualDepsCheck/RustMissingDeps/expected.json, testdata/data/repos/standalone/EclassManualDepsCheck/RustMissingDeps/fix.patch, testdata/repos/standalone/EclassManualDepsCheck/RubyMissingDeps/RubyMissingDeps-0.ebuild, testdata/repos/standalone/EclassManualDepsCheck/RubyMissingDeps/RubyMissingDeps-1.ebuild, testdata/repos/standalone/EclassManualDepsCheck/RubyMissingDeps/RubyMissingDeps-2.ebuild, testdata/repos/standalone/EclassManualDepsCheck/RustMissingDeps/RustMissingDeps-0.ebuild, testdata/repos/standalone/EclassManualDepsCheck/RustMissingDeps/RustMissingDeps-1.ebuild, testdata/repos/standalone/dev-lang/ruby/ruby-0.ebuild, testdata/repos/standalone/dev-ruby/stub/stub-0.ebuild, testdata/repos/standalone/eclass/ruby-ng.eclass, testdata/repos/standalone/virtual/rubygems/rubygems-0.ebuild, testdata/repos/standalone/virtual/rust/rust-0.ebuild
Whn in special modes of eclasses (for example CARGO_OPTIONAL=1), verify specific dependencies are listed somehow in one of the dependencies var.
For commit https://github.com/gentoo/gentoo/commit/2a8a35c8cf88eb696e9ad08e22103b0e94397e7b, I get those results:
```
dev-python/cryptography
RustMissingDeps: version 41.0.3: sets CARGO_OPTIONAL but does not depend on virtual/rust
sys-apps/portage
TmpfilesMissingDeps: version 3.0.45.3-r2: sets TMPFILES_OPTIONAL but does not depend on virtual/tmpfiles
TmpfilesMissingDeps: version 3.0.46: sets TMPFILES_OPTIONAL but does not depend on virtual/tmpfiles
TmpfilesMissingDeps: version 3.0.49-r2: sets TMPFILES_OPTIONAL but does not depend on virtual/tmpfiles
TmpfilesMissingDeps: version 3.0.50: sets TMPFILES_OPTIONAL but does not depend on …
```
=> EclassManualDepsCheck: add check for missing manual deps

src/pkgcheck/checks/codingstyle.py, testdata/data/repos/standalone/DeclarationShadowedCheck/DuplicateFunctionDefinition/expected.json, testdata/data/repos/standalone/DeclarationShadowedCheck/VariableShadowed/expected.json, testdata/data/repos/standalone/DeclarationShadowedCheck/VariableShadowed/fix.patch, testdata/repos/standalone/DeclarationShadowedCheck/DuplicateFunctionDefinition/DuplicateFunctionDefinition-0.ebuild, testdata/repos/standalone/DeclarationShadowedCheck/VariableShadowed/VariableShadowed-0.ebuild
Rules:
- Defined in global scope
- Not inside logic block (so only check top level assignments)
- Doesn't use variable append (`BDEPEND+=""`)
- Doesn't mention self variable inside (`BDEPEND="${BDEPEND} ..."`)
Resolves: https://github.com/pkgcore/pkgcheck/issues/622
=> DeclarationShadowedCheck: new checks to detect shadowed variables & functions

src/pkgcheck/checks/visibility.py, testdata/data/repos/visibility/VisibilityCheck/OldPackageName/expected.json, testdata/repos/visibility/VisibilityCheck/OldPackageName/OldPackageName-0.ebuild, testdata/repos/visibility/profiles/updates/1Q-2024
Resolves: https://github.com/pkgcore/pkgcheck/issues/650
=> OldPackageName: new check for package named after old package name

.git-blame-ignore-revs, pyproject.toml
Same as https://github.com/pkgcore/pkgcore/pull/429 ; I manually audited the history for the rev list and for double checking on who had what contributions, and what contributions still live on despite code reshuffling and variable renames obscuring it.  Marienz is the one who still has intrinsics underneath the various additions and fingerprints.  Not a lot, but core components/contributions.  Things like use addon or metadata checks, although again- it's obscured by the years.  That's still their copyright however.
Finally, Michaeł Górny should be added for obvious reasons.
=> Update git blame ignore list, add mgórny and marienz to authors

src/pkgcheck/checks/git.py, tests/checks/test_git.py
Requested by @juippis, and it indeed seems useful.
Catch cases where new ebuilds are committed with old EAPIs (checks against inherited eclasses). This is checked during `--commits` stage.
Resolves: https://github.com/pkgcore/pkgcheck/issues/666
=> NewerEAPIAvailable: committing new ebuilds with old EAPI

src/pkgcheck/checks/visibility.py, testdata/data/repos/visibility/VisibilityCheck/OldPackageNameDep/expected.json, testdata/repos/visibility/VisibilityCheck/OldPackageNameDep/OldPackageNameDep-0.ebuild
Results on current master. Important to note that some of them block on it's own previous name (like net-analyzer/snmpclitools). Not sure if this is fine or should be whitelisted.
```
games-action/descent1-freedata
OldPackageNameDep: version 1: rdepend: '!games-action/d1x-rebirth' uses old package name which is source of pkgmove, rename into 'games-action/dxx-rebirth'
games-action/descent2-freedata
OldPackageNameDep: version 1: rdepend: '!games-action/d2x-rebirth' uses old package name which is source of pkgmove, rename into 'games-action/dxx-rebirth'
games-action/dxx-rebirth
OldPackageNameDep: version 0.61.0_pre20240630: rdepend: '!<games-action/d1x-rebirth-0.59.100' uses old package name which is source of pkgmove, rename into 'games-action/dxx-rebirth'
OldPackageNameDep: version …
```
=> OldPackageNameDep: check for dependency using pkgmoved name

src/pkgcheck/checks/metadata.py, tests/checks/test_metadata.py
2 years is too aggressive IMHO. See de65ca7b4a3f3a68b65b56e2dcaf6e511d3a3443 for a recent example of this in ::gentoo but there's been plenty of such cases in #gentoo on IRC where we got users upgrading fine but they became unstuck by a removed blocker.
Such blockers are really cheap and the purpose of the warning is really to remove ancient cruft rather than actually obstruct people upgrading systems where it's viable.
Note that it's especially problematic because of the current behaviour of python-exec where emerge won't be able to resume if python-exec got updated but portage hasn't yet been rebuilt w/ new PYTHON_TARGETS.
(... because if any interruption occurs, it can be fatal.)
Bug: https://bugs.gentoo.org/916498
=> OutdatedBlocker: update from 2 years -> 4 years

src/pkgcheck/checks/codingstyle.py, testdata/data/repos/standalone/NonPosixCheck/NonConsistentTarUsage/expected.json, testdata/data/repos/standalone/NonPosixCheck/NonConsistentTarUsage/fix.patch, testdata/repos/standalone/NonPosixCheck/NonConsistentTarUsage/NonConsistentTarUsage-0.ebuild
The ``tar`` command defaults to reading from stdin, unless this default is changed at compile time or the ``TAPE`` environment variable is set.
To ensure consistent behavior, the ``-f`` or ``--file`` option should always be given to ensure the input device is chosen explicitly.
@floppym Here is the check for the issues you found with tar :)
Results for gentoo scan:
```
$ pkgcheck scan -k NonPosixTarUsage
dev-libs/optix
NonPosixTarUsage: version 7.4.0: line 67: non-posix usage of tar without '-f' or '--file': 'tar -zx'
NonPosixTarUsage: version 7.5.0: line 67: non-posix usage of tar without '-f' or '--file': 'tar -zx'
games-action/descent1-data
NonPosixTarUsage: version 1.4a-r1: line 60: non-posix usage of tar without '-f' or '--file': 'tar c \\\n\t\t--mode=u+w \\\n\t\t--ignore-case …
```
=> NonConsistentTarUsage: check tar without -f
